import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import 'react-confirm-alert/src/react-confirm-alert.css'; // Import css
import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });
import 'react-toastify/dist/ReactToastify.css';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <ToastContainer/>
        {children}
        
      </body>
    </html>
  );
}
