import Faculty from '#models/faculty'
import User from '#models/user'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    let user = await User.find(1)
    let user1 = await User.find(2)
    let co1 = await User.find(3)
    let co2 = await User.find(4)
    let co3 = await User.find(5)
    let co4 = await User.find(6)
    let co5 = await User.find(7)
    let std1 = await User.find(9)
    let std2 = await User.find(10)
    let std3 = await User.find(11)
    let std4 = await User.find(12)
    let std5 = await User.find(13)

    let std6 = await User.find(14)
    let std7 = await User.find(15)
    let std8 = await User.find(16)
    let std9 = await User.find(17)
    let std10 = await User.find(18)

    let std11 = await User.find(19)
    let std12 = await User.find(20)
    let std13 = await User.find(21)
    let std14 = await User.find(22)
    let std15 = await User.find(23)

    let std16 = await User.find(24)
    let std17 = await User.find(25)
    let std18 = await User.find(26)
    let std19 = await User.find(27)
    let std20 = await User.find(28)

    let std21 = await User.find(29)
    let std22 = await User.find(30)
    let std23 = await User.find(31)
    let std24 = await User.find(32)
    let std25 = await User.find(33)
    let guest = await User.find(34)
    let guest1 = await User.find(35)
    let guest2 = await User.find(36)
    let guest3 = await User.find(37)
    let guest4 = await User.find(38)
    let faculty = await Faculty.find(1)
    let faculty2 = await Faculty.find(2)
    let faculty3 = await Faculty.find(3)
    let faculty4 = await Faculty.find(4)
    let faculty5 = await Faculty.find(5)

    if (faculty && faculty2 && faculty3 && faculty4 && faculty5) {
      await user?.related('faculty').create(faculty)
      await user1?.related('faculty').create(faculty)
      await co1?.related('faculty').create(faculty)
      await co2?.related('faculty').create(faculty2)
      await co3?.related('faculty').create(faculty3)
      await co4?.related('faculty').create(faculty4)
      await co5?.related('faculty').create(faculty5)
      await std1?.related('faculty').create(faculty)
      await std2?.related('faculty').create(faculty)
      await std3?.related('faculty').create(faculty)
      await std4?.related('faculty').create(faculty)
      await std5?.related('faculty').create(faculty)
      await std6?.related('faculty').create(faculty2)
      await std7?.related('faculty').create(faculty2)
      await std8?.related('faculty').create(faculty2)
      await std9?.related('faculty').create(faculty2)
      await std10?.related('faculty').create(faculty2)
      await std11?.related('faculty').create(faculty3)
      await std12?.related('faculty').create(faculty3)
      await std13?.related('faculty').create(faculty3)
      await std14?.related('faculty').create(faculty3)
      await std15?.related('faculty').create(faculty3)
      await std16?.related('faculty').create(faculty4)
      await std17?.related('faculty').create(faculty4)
      await std18?.related('faculty').create(faculty4)
      await std19?.related('faculty').create(faculty4)
      await std20?.related('faculty').create(faculty4)
      await std21?.related('faculty').create(faculty5)
      await std22?.related('faculty').create(faculty5)
      await std23?.related('faculty').create(faculty5)
      await std24?.related('faculty').create(faculty5)
      await std25?.related('faculty').create(faculty5)
      await guest?.related('faculty').create(faculty)
      await guest1?.related('faculty').create(faculty2)
      await guest2?.related('faculty').create(faculty3)
      await guest3?.related('faculty').create(faculty4)
      await guest4?.related('faculty').create(faculty5)
    }
  }
}