
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import IndexMM from "@/components/pages/IndexMM";
//import { ConfirmProvider } from "material-ui-confirm";


const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>

        <Navbar />
        <IndexMM />
        <Footer />

    </>
  );
}

