'use client'
import React, { useEffect, useState } from 'react';
import Footer from "@/components/layout/Footer";
import NewArticle from '@/components/pages/NewArticle';
import Navbar from '@/components/layout/Navbar';
import { useRouter } from 'next/navigation';
import AuthService from '@/services/AuthService';

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
    const [user, setUser] = useState()
    const router = useRouter()
    useEffect(() => {
        AuthService.profile().then(x => setUser(x.data)).catch(e => router.push('/login'))
    },[])
    if (user) {
        if (user?.roleId !== 4) {
            router.push('/login')
        }
    }
  return (
    <>
      <Navbar />
        {children}
      <Footer />
    </>
  );
}