
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Home from "./page";


const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>

      <Home />
      <Footer />
    </>
  );
}

