
import DashBoardNavBar from "@/components/layout/DashBoardNavBar";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import DetailMM from "@/components/pages/DetailMM";
//import { ConfirmProvider } from "material-ui-confirm";


const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
       <Navbar />
        <div className="flex ">
            <DashBoardNavBar />
            <div className="w-full">
                <div className="p-10">
                    {children}
                </div>
            </div>
        </div>
        <Footer />

    </>
  );
}

